/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exert.wpsjava;

import javax.swing.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        System.setProperty("sun.awt.xembedserver", "true");
        logger.info("启动示例");
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame mainFrame = new JFrame();
                mainFrame.setTitle("WPS JAVA接口调用演示");                       //设置显示窗口标题
                mainFrame.setSize(1524, 768);                           //设置窗口显示尺寸
                mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);       //置窗口是否可以关闭
                mainFrame.setResizable(false);//禁止缩放
                JTabbedPane tabbedPane = new JTabbedPane();
                WpsMainPanel wmp = new WpsMainPanel();
                tabbedPane.add(wmp, "WPS文字");
                // tabbedPane.add(new EtMainPanel(), "WPS表格");
                // tabbedPane.add(new WppMainPanel(), "WPS演示");
                mainFrame.add(tabbedPane);
                mainFrame.setVisible(true); //设置窗口是否可见
            }
        });
    }
}
